# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        in_memory:
            memory:
                users:
                    richard:
                        password: 123
                        roles: 'ROLE_USER'
                    admin:
                        password: admin
                        roles: 'ROLE_ADMIN'

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        user_profile:
            pattern:   ^/login
            anonymous: ~

            form_login:
                login_path: /login
                check_path: /login_check
            http_basic: ~

            logout:
                path:   /logout
                target: /

        main:
            anonymous: ~
            form_login:
                login_path: /login
                check_path: /login_check
            http_basic: ~

            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html

    access_control:
    # require to login for profile view
    - { path: ^/account/showprofile, roles: ROLE_USER }
#    - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
