ride_plan_homepage:
    path:     /hello/{name}
    defaults: { _controller: RidePlanBundle:Default:index }

index:
    path:     /
    defaults: { _controller: RidePlanBundle:StartPage:index }

list:
    path:     /list
    defaults: { _controller: RidePlanBundle:RideList:list }
